### ISSUE TITLE
[Bug] Web Interface Issue on mobile

### ISSUE THREAD

**Issue by c157fl** [help-14/mountain#4]
Hi there,

By pure chance was using Mountain on mobile and noticed that clicking triggers select and not open.
So it only works as a top directory browser.

Thank you for making this.

**Edit: Typo on "too"->"top"

**Comment by help-14** [comment]
> Hi there,
> 
> By pure chance was using Mountain on mobile and noticed that clicking triggers select and not open. So it only works as a too directory browser.
> 
> Thank you for making this.

Hi, what phone are you using?

**Comment by c157fl** [comment]
Ups, my bad, Brave Browser on Android.

**Comment by help-14** [comment]
Seem like double click is not working on touch, changing drag behavior to fix this.

**Comment by help-14** [comment]
The latest dev image should fix problem with select, still need more testing :D

**Comment by c157fl** [comment]
Worked! I can now double click to open the folder. Otherwise I needed to change the url on top to change folder every time 😅.
To deselect I'm doing the "Select -> Select none". 

Not sure when it started to happen but currently I do not see the current folder indicator (attaching image on edit).

**Comment by help-14** [comment]
Mobile UI still have a lot of bugs, will improve later 😂

**Comment by help-14** [comment]
Fixed header menu, breadcrums, control buttons on small screen
