### ISSUE TITLE
[Tweaks] Possible Deselect  Feature Adjustment 

### ISSUE THREAD

**Issue by c157fl** [help-14/mountain#8]
Hi!

I would like to suggest some tweaks on the select system:
 1. The "click outside" to deselect is great on portrait screens but since on vertical the margins are smaller it implies the need to click on the gaps between the files or on the margin of the container. Perhaps it could be extended to include the bar above that shows the current folder?
 2. With multiple files selected, clicking on a selected file will deselect all. Since one can "click outside" to deselect all,would it make more sense to you to have it only deselect the clicked element?

P.S.: Hope you have an awesome 2023!

Cheers

**Comment by help-14** [comment]
yeah it is a easy task, I'm trying to mimic windows explorer so when click on one file will deselect all, maybe a option would be cool.

**Comment by c157fl** [comment]
Ah I see. Hmm, I guess it depends on the habit. Maybe adding an option is a bit overkill. Not sure how many people would notice if not shown/explained directly when opening for the first time on the browser.

**Comment by help-14** [comment]
Yeah, maybe I'll add a welcome screen with options on the first use.
