### ISSUE TITLE
Moving a Directoy into itself creates a recursive file tree

### ISSUE THREAD

**Issue by rM-self-serve** [help-14/mountain#9]
Present in container Digest:sha256:0e01792cdfcb10c6e01fa7a3d4eb27943baf7c0c6f1c87779d014aa4856e6251
![dir1recur](https://user-images.githubusercontent.com/122753594/213639573-f348854e-111e-4d95-8b17-770127b7824b.png)

**Comment by help-14** [comment]
Hi, thank for your feedback, I'll fix it in next update

**Comment by rM-self-serve** [comment]
Things are looking really good! If you can find success in scaling to mobile then I will be extremely interested in forking this repo to create a front end file manager for this device, the ReMarkable Tablet, with a proprietary file format and atypical file operations.
